DROP DATABASE IF EXISTS "monest_users";
CREATE DATABASE "monest_users";

CREATE TABLE "public"."User" (
  id SERIAL PRIMARY KEY NOT NULL,
  password VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  username VARCHAR(255) UNIQUE NOT NULL,
  admin BOOLEAN DEFAULT false,
  "createdAt" TIMESTAMP NOT NULL DEFAULT now()
);