/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

export const awsExports = {
    "aws_project_region": "us-east-1",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_x35b5R7fc",
    "aws_user_pools_web_client_id": "797mk3moh4j7eqaaa116ogbgnn",
    "oauth": {},
};
